image: maven:3.8.4-jdk-11-slim

stages:
  - build_and_test

variables:
  IMAGE_NAME: qub40232046/40232046-graphical-processing-be:$CI_COMMIT_SHORT_SHA

#unit_tests:
#  stage: build_and_test
#  tags: [backend]
#  script:
#    - mvn test

docker_image:
  image: docker:19.03.1
  stage: build_and_test
  tags: [dind]
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD docker.io
    - export DOCKER_CLI_EXPERIMENTAL=enabled
#    - docker buildx create --name builder
#    - docker buildx use builder
    - docker buildx build --push --platform linux/arm64,linux/amd64 --tag $IMAGE_NAME .
