image: maven:3.8.4-jdk-11-slim

stages:
#  - test_image_and_unit_tests
  - acceptance

#build_test_image:
#  image: docker:19.03.1
#  stage: test_image_and_unit_tests
#  tags: [dind]
#  variables:
##    DOCKER_HOST: tcp://dockerdaemon:2376 this is not currently the host due to cert issues - it is tcp://docker:2376
#    DOCKER_TLS_CERTDIR: "/certs"
#  services:
#    - docker:19.03.1-dind
#  script:
#    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER docker.io --password-stdin
#    - docker build -t $CI_REGISTRY:$CI_COMMIT_SHORT_SHA .
#    - docker push $CI_REGISTRY
#
#unit_tests:
#  stage: test_image_and_unit_tests
#  tags: [backend]
#  script:
#    - mvn test

integration_tests:
  stage: acceptance
  tags: [dind]
  image:
    name: qub40232046/newman
    entrypoint: [ "" ]
  services:
    - name: $CI_REGISTRY
      alias: graphical-csv-processing-api
  script:
    - newman run /builds/40232046/graphical-csv-processing-be/integration/collection.json --working-dir "/builds/40232046/graphical-csv-processing-be/integration" --env-var "baseUrl=graphical-csv-processing-api:8080"

# will execute integration tests here also
# tried and failed with docker multi arch builds => not necessary can be a future improvement