image: maven:3.8.4-jdk-11-slim

stages:
  - build_and_test

variables:
  IMAGE_NAME: qub40232046/40232046-graphical-processing-be:$CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

#unit_tests:
#  stage: build_and_test
#  tags: [backend]
#  script:
#    - mvn test

#docker_image:
#  image: docker:20.10.7
#  stage: build_and_test
#  tags: [dind]
#  services:
#    - docker:20.10.7-dind
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD docker.io
##    - export DOCKER_CLI_EXPERIMENTAL=enabled
##    - docker buildx version
#    - docker buildx create --use
#    - docker buildx build --push --platform linux/arm64,linux/amd64 --tag $IMAGE_NAME .

docker-build-master:
  image: roughcoon/buildx:v0.1.1
  stage: build_and_test
  tags: [dind]
  services:
    - docker:20.10-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" docker.io
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes; docker buildx create --use
    - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag "$CI_REGISTRY_IMAGE" .
  only:
    - master