image: maven:3.8.4-jdk-11-slim

stages:
  - unit_test

unit_tests:
  stage: unit_test
  tags: [backend]
  script:
    - mvn test

# will execute integration tests here also
# tried and failed with docker multi arch builds => not necessary can be a future improvement