image: maven:3.8.4-jdk-11-slim

stages:
  - create_image_and_unit_test
  - acceptance_test
  - update_image

build_test_image:
  stage: create_image_and_unit_test
  tags: [dind]
  image: qub40232046/docker-buildx:19.03.1
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.1-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER docker.io --password-stdin
    - docker context create buildx-builder
    - docker buildx create buildx-builder
    - docker buildx build --push --platform linux/arm64,linux/amd64 --tag $CI_REGISTRY:$CI_COMMIT_SHORT_SHA .

unit_tests:
  stage: create_image_and_unit_test
  tags: [backend]
  script:
    - mvn test

integration_tests:
  stage: acceptance_test
  tags: [dind]
  image:
    name: qub40232046/newman
    entrypoint: [ "" ]
  services:
    - name: $CI_REGISTRY:$CI_COMMIT_SHORT_SHA
      alias: graphical-csv-processing-api
  script:
    - cd /builds/40232046/graphical-csv-processing-be/integration
    - newman run collection.json --env-var "base_url=graphical-csv-processing-api:8080"

retag_image:
  stage: update_image
  tags: [ dind ]
  image: docker:19.03.1
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.1-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER docker.io --password-stdin
    - docker pull $CI_REGISTRY:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY:$CI_COMMIT_SHORT_SHA $CI_REGISTRY
    - docker push $CI_REGISTRY
  only:
    - master